Feature/product crud
Pak-Thani/consumer-api pull request #10
Opened 2022-09-14 16:06 UTC by RaidyMR

## Issue / Task
resolved Pak-Thani/consumer-api#2 
- [x] Pengguna dan Pengguna Internal dapat melihat detail dari produk yang ada
- [x] Pengguna Internal dapat melihat list of produk yang ada (django admin)
- [x] Pengguna Internal dapat update dan delete produk yang ada (django admin)

## Summary

Semua Kriteria Telah Diselesaikan

## Test Plan
### Hasil Tes user Melihat Detail Produk
![image](https://user-images.githubusercontent.com/92345334/190201672-d173002e-88c3-4819-8264-0610f6846177.png)

### Tes user Melihat Detail Produk Tidak Ditemukan
![image](https://user-images.githubusercontent.com/92345334/190205569-4f6ce94b-4034-4c7d-9849-7c8459736323.png)

### Halaman Admin Untuk melakukan CRUD
![image](https://user-images.githubusercontent.com/92345334/190205822-5307274c-ae11-4748-9037-a1f1b0aaf471.png)

2022-09-14 16:07 UTC, luthfianum approved these changes
LGTM!

2022-09-15 10:10 UTC, manokrajin commented
LGTM!

2022-09-15 10:15 UTC, manokrajin approved these changes

2022-09-15 10:29 UTC, muhammadhafizm requested changes

2022-09-15 10:29 UTC, muhammadhafizm commented on product/models.py
ada field yang kurang, qty dan stockAvailabelity. apa di ERD belum di tambah ya? cmiw : @manokrajin 
<img width="1272" alt="Screen Shot 2022-09-15 at 17 28 15" src="https://user-images.githubusercontent.com/76779078/190381331-48b7022a-979d-4b67-8cfb-aacbd607556e.png">

2022-09-15 10:30 UTC, muhammadhafizm reviewed
overall response good, tapi ada field yang kurang. need changes ya

2022-09-15 15:31 UTC, RaidyMR commented
@muhammadhafizm Sudah ku push perubahannya mas. Mohon Di review kembali 🙏

2022-09-16 07:46 UTC, merged